name       : libp11-kit
version    : 0.23.10
release    : 12
source     :
    - https://github.com/p11-glue/p11-kit/releases/download/0.23.10/p11-kit-0.23.10.tar.gz : f9212a3f225ef543e13fae9945527d66c0cbb67246320035dd94fab2bce5ae43
homepage   : https://p11-glue.github.io/p11-glue/p11-kit.html
license    : GPL-2.0
component  : security.crypto
emul32     : yes
summary    : The p11-kit package Provides a way to load and enumerate PKCS#11 (a Cryptographic Token Interface Standard) modules
description: |
    The p11-kit package Provides a way to load and enumerate PKCS #11 (a Cryptographic Token Interface Standard) modules.
builddeps  :
    - pkgconfig32(libffi)
    - pkgconfig32(libtasn1)
setup      : |
    %configure --disable-static \
        --with-system-config="/usr/share/defaults/pkcs11" \
        --with-user-config="/etc/pkcs11"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
