name       : libp11-kit
version    : 0.24.0
release    : 20
source     :
    - https://github.com/p11-glue/p11-kit/releases/download/0.24.0/p11-kit-0.24.0.tar.xz : 81e6140584f635e4e956a1b93a32239acf3811ff5b2d3a5c6094e94e99d2c685
homepage   : https://p11-glue.github.io/p11-glue/p11-kit.html
license    : GPL-2.0-or-later
component  : security.crypto
emul32     : yes
summary    : The p11-kit package Provides a way to load and enumerate PKCS#11 (a Cryptographic Token Interface Standard) modules
description: |
    The p11-kit package Provides a way to load and enumerate PKCS #11 (a Cryptographic Token Interface Standard) modules.
builddeps  :
    - pkgconfig(libsystemd)
    - pkgconfig32(libffi)
    - pkgconfig32(libtasn1)
setup      : |
    exOpts=""
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exOpts="--without-systemd"
    fi

    %configure --disable-static \
        --with-system-config="/usr/share/defaults/pkcs11" \
        --with-user-config="/etc/pkcs11" $exOpts
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests work when running make check manually in the chroot
    %make check || :
