name       : libp11-kit
version    : 0.23.2
release    : 9
source     :
    - https://p11-glue.freedesktop.org/releases/p11-kit-0.23.2.tar.gz : ba726ea8303c97467a33fca50ee79b7b35212964be808ecf9b145e9042fdfaf0
homepage   : http://p11-glue.freedesktop.org/p11-kit.html
license    :
    - GPL-2.0
summary    : The p11-kit package Provides a way to load and enumerate PKCS  #11 (a Cryptographic Token Interface Standard) modules.
builddeps  :
    - pkgconfig(libtasn1)
    - pkgconfig32(libtasn1)
    - pkgconfig32(libffi)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The p11-kit package Provides a way to load and enumerate PKCS #11 (a Cryptographic Token Interface Standard) modules.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
